export const IPC = {
  getSnapshot: 'lyriclens:get-snapshot',
  updateSettings: 'lyriclens:update-settings',
  perform: 'lyriclens:perform',
  setTranslationKey: 'lyriclens:set-translation-key',
  clearTranslationKey: 'lyriclens:clear-translation-key',
  testTranslation: 'lyriclens:test-translation',
  demoCommand: 'lyriclens:demo-command',
  library: {
    lookupWord: 'lyriclens:library:lookup-word',
    saveWord: 'lyriclens:library:save-word',
    removeWord: 'lyriclens:library:remove-word',
    setFavorite: 'lyriclens:library:set-favorite',
    removeHistory: 'lyriclens:library:remove-history',
    clearHistory: 'lyriclens:library:clear-history',
    getSong: 'lyriclens:library:get-song',
  },
  dragStart: 'lyriclens:drag-start',
  dragMove: 'lyriclens:drag-move',
  dragEnd: 'lyriclens:drag-end',
  evt: {
    playback: 'lyriclens:evt:playback',
    lyrics: 'lyriclens:evt:lyrics',
    settings: 'lyriclens:evt:settings',
    spotify: 'lyriclens:evt:spotify',
    providers: 'lyriclens:evt:providers',
    shortcutStatus: 'lyriclens:evt:shortcut-status',
    library: 'lyriclens:evt:library',
    navigate: 'lyriclens:evt:navigate',
    notice: 'lyriclens:evt:notice',
  },
} as const;
